# GGR274 Lab 4: Introduction to Data Wrangling, Part 1

## Logistics

Like last week, our lab grade will be based on attendance and submission of a few small tasks to MarkUs during the lab session (or by 23:59 on Thursday).

Complete the tasks in this Jupyter notebook and submit your completed file to [MarkUs](https://markus-ds.teach.cs.toronto.edu).
Here are the instructions for submitting to MarkUs (same as last week):

1. Download this file (`Lab_4.ipynb`) from JupyterHub. (See [our JupyterHub Guide](../../../guides/jupyterhub_guide.ipynb) for detailed instructions.)
2. Submit this file to MarkUs under the **lab4** assignment. (See [our MarkUs Guide](../../../guides/markus_guide.ipynb) for detailed instructions.)

Note: there's no autograding set up for this week's lab, but your TA will be checking that your submitted lab file is complete as part of your "lab attendance" grade.

## Task 1: Read the csv file into a `DataFrame`

Read the csv file `ArrestsStripSearches.csv` into a pandas Dataframe called `police_df` related to Toronto Police Race and Identity Based Data - Arrests and Strip Searches.

_The file is located in the same folder as the notebook._

In [8]:
import pandas as pd
# Read the CSV file into a DataFrame
police_df = pd.read_csv("ArrestsStripSearches.csv")
police_df

,_id,Arrest_Year,Arrest_Month,EventID,ArrestID,PersonID,Perceived_Race,Sex,Age_group__at_arrest_,Youth_at_arrest__under_18_years,...,Actions_at_arrest___Resisted__d,Actions_at_arrest___Mental_inst,Actions_at_arrest___Assaulted_o,Actions_at_arrest___Cooperative,SearchReason_CauseInjury,SearchReason_AssistEscape,SearchReason_PossessWeapons,SearchReason_PossessEvidence,ItemsFound,ObjectId
0,1,2020,July-Sept,1005907,6017884.0,326622,White,M,Aged 35 to 44 years,Not a youth,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1
1,2,2020,July-Sept,1014562,6056669.0,326622,White,M,Aged 35 to 44 years,Not a youth,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
2,3,2020,Oct-Dec,1029922,6057065.0,326622,Unknown or Legacy,M,Aged 35 to 44 years,Not a youth,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
3,4,2021,Jan-Mar,1052190,6029059.0,327535,Black,M,Aged 25 to 34 years,Not a youth,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
4,5,2021,Jan-Mar,1015512,6040372.0,327535,South Asian,M,Aged 25 to 34 years,Not a youth,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65271,65272,2021,Oct-Dec,1055609,6044336.0,316123,Indigenous,F,Aged 25 to 34 years,Not a youth,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65272
65272,65273,2021,Oct-Dec,1032758,6031692.0,307736,South Asian,M,Aged 35 to 44 years,Not a youth,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65273
65273,65274,2021,Oct-Dec,1021067,6064396.0,324057,White,F,Aged 45 to 54 years,Not a youth,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65274
65274,65275,2021,Oct-Dec,1008998,6008662.0,331870,Unknown or Legacy,M,Aged 17 years and under,Youth (aged 17 years and under),...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,65275
65275,65276,2021,Oct-Dec,1033395,6032145.0,310583,Latino,M,Aged 18 to 24 years,Not a youth,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,65276

In [9]:
police_df.describe()

,_id,Arrest_Year,EventID,ArrestID,PersonID,StripSearch,Booked,Actions_at_arrest___Concealed_i,Actions_at_arrest___Combative__,Actions_at_arrest___Resisted__d,Actions_at_arrest___Mental_inst,Actions_at_arrest___Assaulted_o,Actions_at_arrest___Cooperative,SearchReason_CauseInjury,SearchReason_AssistEscape,SearchReason_PossessWeapons,SearchReason_PossessEvidence,ItemsFound,ObjectId
count,65276.000000,65276.000000,6.527600e+04,6.480700e+04,65276.000000,7801.0,33911.0,266.0,2881.0,2502.0,2179.0,415.0,29109.0,7801.000000,7801.000000,7801.000000,7801.000000,7801.000000,65276.000000
mean,32638.500000,2020.510096,1.029998e+06,6.032402e+06,318599.919695,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.765671,0.343161,0.453403,0.418921,0.373157,32638.500000
std,18843.702423,0.499902,1.731809e+04,1.870751e+04,10815.387928,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.423606,0.474795,0.497856,0.493414,0.483674,18843.702423
min,1.000000,2020.000000,1.000000e+06,6.000000e+06,300000.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,16319.750000,2020.000000,1.015001e+06,6.016202e+06,309215.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,0.000000,0.000000,0.000000,0.000000,16319.750000
50%,32638.500000,2021.000000,1.030006e+06,6.032402e+06,318595.500000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,0.000000,0.000000,0.000000,0.000000,32638.500000
75%,48957.250000,2021.000000,1.044996e+06,6.048602e+06,327926.250000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,48957.250000
max,65276.000000,2021.000000,1.060002e+06,6.064804e+06,337346.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,65276.000000

In [9]:
police_df.describe()

,_id,Arrest_Year,EventID,ArrestID,PersonID,StripSearch,Booked,Actions_at_arrest___Concealed_i,Actions_at_arrest___Combative__,Actions_at_arrest___Resisted__d,Actions_at_arrest___Mental_inst,Actions_at_arrest___Assaulted_o,Actions_at_arrest___Cooperative,SearchReason_CauseInjury,SearchReason_AssistEscape,SearchReason_PossessWeapons,SearchReason_PossessEvidence,ItemsFound,ObjectId
count,65276.000000,65276.000000,6.527600e+04,6.480700e+04,65276.000000,7801.0,33911.0,266.0,2881.0,2502.0,2179.0,415.0,29109.0,7801.000000,7801.000000,7801.000000,7801.000000,7801.000000,65276.000000
mean,32638.500000,2020.510096,1.029998e+06,6.032402e+06,318599.919695,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.765671,0.343161,0.453403,0.418921,0.373157,32638.500000
std,18843.702423,0.499902,1.731809e+04,1.870751e+04,10815.387928,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.423606,0.474795,0.497856,0.493414,0.483674,18843.702423
min,1.000000,2020.000000,1.000000e+06,6.000000e+06,300000.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,16319.750000,2020.000000,1.015001e+06,6.016202e+06,309215.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,0.000000,0.000000,0.000000,0.000000,16319.750000
50%,32638.500000,2021.000000,1.030006e+06,6.032402e+06,318595.500000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,0.000000,0.000000,0.000000,0.000000,32638.500000
75%,48957.250000,2021.000000,1.044996e+06,6.048602e+06,327926.250000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,48957.250000
max,65276.000000,2021.000000,1.060002e+06,6.064804e+06,337346.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,65276.000000

In [10]:
police_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65276 entries, 0 to 65275
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   _id                              65276 non-null  int64
 1   Arrest_Year                      65276 non-null  int64
 2   Arrest_Month                     65276 non-null  object
 3   EventID                          65276 non-null  int64
 4   ArrestID                         64807 non-null  float64
 5   PersonID                         65276 non-null  int64
 6   Perceived_Race                   65272 non-null  object
 7   Sex                              65276 non-null  object
 8   Age_group__at_arrest_            65252 non-null  object
 9   Youth_at_arrest__under_18_years  65276 non-null  object
 10  ArrestLocDiv                     65276 non-null  object
 11  StripSearch                      7801 non-null   float64
 12  Booked                           33911 non-null  float64
 13  Occurrence_Category              65111 non-null  object
 14  Actions_at_arrest___Concealed_i  266 non-null    float64
 15  Actions_at_arrest___Combative__  2881 non-null   float64
 16  Actions_at_arrest___Resisted__d  2502 non-null   float64
 17  Actions_at_arrest___Mental_inst  2179 non-null   float64
 18  Actions_at_arrest___Assaulted_o  415 non-null    float64
 19  Actions_at_arrest___Cooperative  29109 non-null  float64
 20  SearchReason_CauseInjury         7801 non-null   float64
 21  SearchReason_AssistEscape        7801 non-null   float64
 22  SearchReason_PossessWeapons      7801 non-null   float64
 23  SearchReason_PossessEvidence     7801 non-null   float64
 24  ItemsFound                       7801 non-null   float64
 25  ObjectId                         65276 non-null  int64
dtypes: float64(14), int64(5), object(7)
memory usage: 12.9+ MB

## Task 2: Create a `DataFrame` of arrests in 2021

### a. Subset the tabular data by rows

- Create a boolean variable named `Arrests_2021` computed from `police_df` that is `True` if `Arrest_Year` is `2021` and `False` otherwise.

- Use `Arrests_2021` to select rows of `police_df` that correspond to arrests in 2021.  Save this new DataFrame in a variable called `police_2021_df`.  Examine the `head()` of this `DataFrame`.

In [79]:
Arrests_2021 = police_df["Arrest_Year"] == 2021
police_2021_df = Arrests_2021
police_2021_df.head()

0    False
1    False
2    False
3     True
4     True
Name: Arrest_Year, dtype: bool

In [80]:
Arrests_2021 = police_df["Arrest_Year"] == 2021
police_2021_df = police_df[Arrests_2021]
police_2021_df

,_id,Arrest_Year,Arrest_Month,EventID,ArrestID,PersonID,Perceived_Race,Sex,Age_group__at_arrest_,Youth_at_arrest__under_18_years,...,Actions_at_arrest___Resisted__d,Actions_at_arrest___Mental_inst,Actions_at_arrest___Assaulted_o,Actions_at_arrest___Cooperative,SearchReason_CauseInjury,SearchReason_AssistEscape,SearchReason_PossessWeapons,SearchReason_PossessEvidence,ItemsFound,ObjectId
3,4,2021,Jan-Mar,1052190,6029059.0,327535,Black,M,Aged 25 to 34 years,Not a youth,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
4,5,2021,Jan-Mar,1015512,6040372.0,327535,South Asian,M,Aged 25 to 34 years,Not a youth,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
5,6,2021,Apr-June,1019145,6060688.0,327535,South Asian,M,Aged 25 to 34 years,Not a youth,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,6
6,7,2021,Jan-Mar,1035445,6053833.0,330778,Black,M,Aged 25 to 34 years,Not a youth,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
7,8,2021,Jan-Mar,1050464,6063477.0,330778,Black,M,Aged 25 to 34 years,Not a youth,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65271,65272,2021,Oct-Dec,1055609,6044336.0,316123,Indigenous,F,Aged 25 to 34 years,Not a youth,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65272
65272,65273,2021,Oct-Dec,1032758,6031692.0,307736,South Asian,M,Aged 35 to 44 years,Not a youth,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65273
65273,65274,2021,Oct-Dec,1021067,6064396.0,324057,White,F,Aged 45 to 54 years,Not a youth,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65274
65274,65275,2021,Oct-Dec,1008998,6008662.0,331870,Unknown or Legacy,M,Aged 17 years and under,Youth (aged 17 years and under),...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,65275
65275,65276,2021,Oct-Dec,1033395,6032145.0,310583,Latino,M,Aged 18 to 24 years,Not a youth,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,65276

In [81]:
police_2021_df.describe()

,_id,Arrest_Year,EventID,ArrestID,PersonID,StripSearch,Booked,Actions_at_arrest___Concealed_i,Actions_at_arrest___Combative__,Actions_at_arrest___Resisted__d,Actions_at_arrest___Mental_inst,Actions_at_arrest___Assaulted_o,Actions_at_arrest___Cooperative,SearchReason_CauseInjury,SearchReason_AssistEscape,SearchReason_PossessWeapons,SearchReason_PossessEvidence,ItemsFound,ObjectId
count,33297.000000,33297.0,3.329700e+04,3.327400e+04,33297.000000,686.0,16815.0,119.0,1449.0,1315.0,1071.0,209.0,14568.0,686.000000,686.000000,686.000000,686.000000,686.000000,33297.000000
mean,33761.888068,2021.0,1.030080e+06,6.032405e+06,318568.944109,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.558309,0.039359,0.303207,0.529155,0.080175,33761.888068
std,19739.852960,0.0,1.736915e+04,1.869798e+04,10789.261905,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.496951,0.194589,0.459979,0.499513,0.271762,19739.852960
min,4.000000,2021.0,1.000000e+06,6.000000e+06,300003.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000
25%,16606.000000,2021.0,1.015054e+06,6.016152e+06,309210.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,16606.000000
50%,33349.000000,2021.0,1.030106e+06,6.032468e+06,318597.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,0.000000,0.000000,1.000000,0.000000,33349.000000
75%,50597.000000,2021.0,1.045172e+06,6.048501e+06,327799.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,0.000000,1.000000,1.000000,0.000000,50597.000000
max,65276.000000,2021.0,1.060000e+06,6.064804e+06,337345.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,65276.000000

In [82]:
police_2021_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 33297 entries, 3 to 65275
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   _id                              33297 non-null  int64
 1   Arrest_Year                      33297 non-null  int64
 2   Arrest_Month                     33297 non-null  object
 3   EventID                          33297 non-null  int64
 4   ArrestID                         33274 non-null  float64
 5   PersonID                         33297 non-null  int64
 6   Perceived_Race                   33295 non-null  object
 7   Sex                              33297 non-null  object
 8   Age_group__at_arrest_            33284 non-null  object
 9   Youth_at_arrest__under_18_years  33297 non-null  object
 10  ArrestLocDiv                     33297 non-null  object
 11  StripSearch                      686 non-null    float64
 12  Booked                           16815 non-null  float64
 13  Occurrence_Category              33132 non-null  object
 14  Actions_at_arrest___Concealed_i  119 non-null    float64
 15  Actions_at_arrest___Combative__  1449 non-null   float64
 16  Actions_at_arrest___Resisted__d  1315 non-null   float64
 17  Actions_at_arrest___Mental_inst  1071 non-null   float64
 18  Actions_at_arrest___Assaulted_o  209 non-null    float64
 19  Actions_at_arrest___Cooperative  14568 non-null  float64
 20  SearchReason_CauseInjury         686 non-null    float64
 21  SearchReason_AssistEscape        686 non-null    float64
 22  SearchReason_PossessWeapons      686 non-null    float64
 23  SearchReason_PossessEvidence     686 non-null    float64
 24  ItemsFound                       686 non-null    float64
 25  ObjectId                         33297 non-null  int64
dtypes: float64(14), int64(5), object(7)
memory usage: 6.9+ MB

In [83]:
police_2021_df.head()

,_id,Arrest_Year,Arrest_Month,EventID,ArrestID,PersonID,Perceived_Race,Sex,Age_group__at_arrest_,Youth_at_arrest__under_18_years,...,Actions_at_arrest___Resisted__d,Actions_at_arrest___Mental_inst,Actions_at_arrest___Assaulted_o,Actions_at_arrest___Cooperative,SearchReason_CauseInjury,SearchReason_AssistEscape,SearchReason_PossessWeapons,SearchReason_PossessEvidence,ItemsFound,ObjectId
3,4,2021,Jan-Mar,1052190,6029059.0,327535,Black,M,Aged 25 to 34 years,Not a youth,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
4,5,2021,Jan-Mar,1015512,6040372.0,327535,South Asian,M,Aged 25 to 34 years,Not a youth,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
5,6,2021,Apr-June,1019145,6060688.0,327535,South Asian,M,Aged 25 to 34 years,Not a youth,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,6
6,7,2021,Jan-Mar,1035445,6053833.0,330778,Black,M,Aged 25 to 34 years,Not a youth,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
7,8,2021,Jan-Mar,1050464,6063477.0,330778,Black,M,Aged 25 to 34 years,Not a youth,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,8

## b. Inspect columns of the tabular data

- Create a variable called `Arrest_column_names` that stores a list of the column names of `police_2021_df` and print the list.

In [84]:
Arrest_column_names = list(police_2021_df.columns)
print("Column names of police_2021_df:")
for column_name in Arrest_column_names:
    print(f"- {column_name}")

Column names of police_2021_df:
- _id
- Arrest_Year
- Arrest_Month
- EventID
- ArrestID
- PersonID
- Perceived_Race
- Sex
- Age_group__at_arrest_
- Youth_at_arrest__under_18_years
- ArrestLocDiv
- StripSearch
- Booked
- Occurrence_Category
- Actions_at_arrest___Concealed_i
- Actions_at_arrest___Combative__
- Actions_at_arrest___Resisted__d
- Actions_at_arrest___Mental_inst
- Actions_at_arrest___Assaulted_o
- Actions_at_arrest___Cooperative
- SearchReason_CauseInjury
- SearchReason_AssistEscape
- SearchReason_PossessWeapons
- SearchReason_PossessEvidence
- ItemsFound
- ObjectId

## Task 3: Select columns from `police_2021_df` and examine the distributions of each column

- Create a new DataFrame from `police_2021_df` with the following columns: `_id`, `Sex`,` Perceived_Race`, `SearchReason_PossessWeapons` and assign it to the variable `police_2021_raceweapons`.  Examine the `head()` of this `DataFrame`.

- Use `.value_counts()` to compute the distributions of `Sex`, `Perceived_Race`, `SearchReason_PossessWeapons`. You do not need to save these values in variables, though you may do so if you want.

## Variations of `police_2021_df` with examination of distributions of each column

I computed both sections of **Task 3** in various ways:

1. Within the first output, I removed the index colum via `to_markdown(index=False)` and computed the whole task all together. This was done by `!pip install tabulate` on a separate tab within the JupyterLab Interface.
2. Seeing as it is, I tried to do both tasks of this section separately in the second and third output, to see how the table format for the output works differently. It displayed only 5 rows so I instead gave a command to display 25 rows via `police_2021_raceweapons.head(25)`.
3. In Output #3, you can see that I still removed the index column, but also had a sort of makeshift table format for output again, like Output #1. What was insightful was the force command to display 25 rows before this. Why? Because I noticed within the search reason output, it had 1, 0, and also, **NaN**. But within the output, it only showed the count for 1 and 0.
4. Hence, Output #4 incorporates `(dropna=False)` in order to include NaN within the count. Without it, we were missing 57475 counts within that section.
5. The last two outputs (#5 and #6) just displays the output with the index colum included. Output #6 does not have lines to separate the output values and colums, in order to follow a more traditional table format.

In [88]:
police_2021_raceweapons = police_2021_df[['_id', 'Sex', 'Perceived_Race', 'SearchReason_PossessWeapons']]
police_2021_raceweapons

         _id Sex     Perceived_Race  SearchReason_PossessWeapons
3          4   M              Black                          NaN
4          5   M        South Asian                          NaN
5          6   M        South Asian                          NaN
6          7   M              Black                          NaN
7          8   M              Black                          NaN
...      ...  ..                ...                          ...
65271  65272   F         Indigenous                          NaN
65272  65273   M        South Asian                          NaN
65273  65274   F              White                          NaN
65274  65275   M  Unknown or Legacy                          NaN
65275  65276   M             Latino                          NaN

[33297 rows x 4 columns]

In [92]:
# Assuming police_2021_raceweapons is your DataFrame with the specified columns
sex_distribution = police_2021_raceweapons['Sex'].value_counts()
race_distribution = police_2021_raceweapons['Perceived_Race'].value_counts()
search_reason_distribution = police_2021_raceweapons['SearchReason_PossessWeapons'].value_counts()
# Save to Excel file
police_2021_raceweapons.to_excel('police_2021_raceweapons_with_distributions.xlsx', index=False)

# Print the distributions
print("Sex Distribution:\n", sex_distribution)
print("\nPerceived Race Distribution:\n", race_distribution)
print("\nSearch Reason Distribution:\n", search_reason_distribution)

Sex Distribution:
 Sex
M    26815
F     6479
U        3
Name: count, dtype: int64

Perceived Race Distribution:
 Perceived_Race
White                   14116
Black                    8878
Unknown or Legacy        2444
East/Southeast Asian     2361
South Asian              1871
Middle-Eastern           1730
Latino                    960
Indigenous                935
Name: count, dtype: int64

Search Reason Distribution:
 SearchReason_PossessWeapons
0.0    478
1.0    208
Name: count, dtype: int64

In [93]:
police_2021_raceweapons.head()

   _id Sex Perceived_Race  SearchReason_PossessWeapons
3    4   M          Black                          NaN
4    5   M    South Asian                          NaN
5    6   M    South Asian                          NaN
6    7   M          Black                          NaN
7    8   M          Black                          NaN